package com.example.network

import com.example.BuildConfig
import com.example.data.model.UserProfile
import com.example.data.model.WorkoutPlan
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {

    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    suspend fun generateAiWorkoutPlan(
        user: UserProfile,
        availableEquipment: String,
        workoutTimeMinutes: Int
    ): WorkoutPlan = withContext(Dispatchers.IO) {
        val apiKey = try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Exception) {
            ""
        }

        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            // Smart AI Local Generation Fallback
            return@withContext WorkoutPlan(
                title = "AI Personalized ${user.fitnessGoal} Plan",
                category = user.fitnessLevel,
                type = "AI Custom Split",
                description = "Customized ${workoutTimeMinutes}-minute routine tailored for ${user.fitnessGoal} using $availableEquipment.",
                durationMin = workoutTimeMinutes,
                totalExercises = 6,
                caloriesBurned = (workoutTimeMinutes * 8.5).toInt(),
                difficulty = user.fitnessLevel,
                isCustom = true
            )
        }

        try {
            val prompt = """
                You are FitPro AI Master Fitness Coach. Create a personalized workout plan for a user with these stats:
                Age: ${user.age}, Gender: ${user.gender}, Height: ${user.heightCm} cm, Weight: ${user.weightKg} kg,
                Fitness Level: ${user.fitnessLevel}, Fitness Goal: ${user.fitnessGoal},
                Available Equipment: $availableEquipment, Target Workout Time: $workoutTimeMinutes minutes.
                
                Respond in valid JSON with format:
                {
                   "title": "Short Punchy Workout Name",
                   "category": "${user.fitnessLevel}",
                   "type": "AI Custom Split",
                   "description": "Short 2 sentence overview of why this plan works for the user.",
                   "durationMin": $workoutTimeMinutes,
                   "totalExercises": 6,
                   "caloriesBurned": 380,
                   "difficulty": "${user.fitnessLevel}"
                }
            """.trimIndent()

            val jsonBody = JSONObject().apply {
                put("contents", JSONArray().apply {
                    put(JSONObject().apply {
                        put("parts", JSONArray().apply {
                            put(JSONObject().put("text", prompt))
                        })
                    })
                })
            }

            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            val responseString = response.body?.string() ?: ""

            if (response.isSuccessful && responseString.isNotBlank()) {
                val jsonResp = JSONObject(responseString)
                val textResp = jsonResp.getJSONArray("candidates")
                    .getJSONObject(0)
                    .getJSONObject("content")
                    .getJSONArray("parts")
                    .getJSONObject(0)
                    .getString("text")

                // Extract JSON substring
                val jsonStart = textResp.indexOf("{")
                val jsonEnd = textResp.lastIndexOf("}")
                if (jsonStart != -1 && jsonEnd != -1) {
                    val parsedObj = JSONObject(textResp.substring(jsonStart, jsonEnd + 1))
                    return@withContext WorkoutPlan(
                        title = parsedObj.optString("title", "AI Smart Workout Plan"),
                        category = parsedObj.optString("category", user.fitnessLevel),
                        type = parsedObj.optString("type", "AI Custom Split"),
                        description = parsedObj.optString("description", "Tailored workout routine generated by FitPro AI."),
                        durationMin = parsedObj.optInt("durationMin", workoutTimeMinutes),
                        totalExercises = parsedObj.optInt("totalExercises", 6),
                        caloriesBurned = parsedObj.optInt("caloriesBurned", 350),
                        difficulty = parsedObj.optString("difficulty", user.fitnessLevel),
                        isCustom = true
                    )
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        // Fallback
        WorkoutPlan(
            title = "AI ${user.fitnessGoal} Plan",
            category = user.fitnessLevel,
            type = "AI Custom Split",
            description = "Customized $workoutTimeMinutes-min routine designed for ${user.fitnessGoal} with $availableEquipment.",
            durationMin = workoutTimeMinutes,
            totalExercises = 6,
            caloriesBurned = (workoutTimeMinutes * 7.5).toInt(),
            difficulty = user.fitnessLevel,
            isCustom = true
        )
    }

    suspend fun chatWithAiTrainer(userPrompt: String, user: UserProfile): String = withContext(Dispatchers.IO) {
        val apiKey = try { BuildConfig.GEMINI_API_KEY } catch (e: Exception) { "" }

        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext getOfflineTrainerResponse(userPrompt, user)
        }

        try {
            val systemInstruction = "You are FitPro AI, an encouraging, elite certified personal trainer and sports nutritionist. Keep advice practical, safe, motivating, and concise (under 120 words)."
            val fullPrompt = "User Profile: Goal=${user.fitnessGoal}, Level=${user.fitnessLevel}, Weight=${user.weightKg}kg.\nUser Question: $userPrompt"

            val jsonBody = JSONObject().apply {
                put("contents", JSONArray().apply {
                    put(JSONObject().apply {
                        put("parts", JSONArray().apply {
                            put(JSONObject().put("text", "$systemInstruction\n\n$fullPrompt"))
                        })
                    })
                })
            }

            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            val responseString = response.body?.string() ?: ""

            if (response.isSuccessful && responseString.isNotBlank()) {
                val jsonResp = JSONObject(responseString)
                val textResp = jsonResp.getJSONArray("candidates")
                    .getJSONObject(0)
                    .getJSONObject("content")
                    .getJSONArray("parts")
                    .getJSONObject(0)
                    .getString("text")
                return@withContext textResp
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        return@withContext getOfflineTrainerResponse(userPrompt, user)
    }

    private fun getOfflineTrainerResponse(userPrompt: String, user: UserProfile): String {
        val lower = userPrompt.lowercase()
        return when {
            "diet" in lower || "protein" in lower || "food" in lower ->
                "For your goal of ${user.fitnessGoal}, aim for 1.6-2.2g of protein per kg of body weight (${(user.weightKg * 1.8).toInt()}g/day). Prioritize lean chicken, eggs, Greek yogurt, salmon, and oats."
            "water" in lower || "hydrate" in lower ->
                "Optimal hydration enhances workout performance by up to 25%! Drink 3000ml of water daily, adding an extra 500ml on intense training days."
            "fat" in lower || "weight loss" in lower || "cardio" in lower ->
                "To accelerate fat loss, combine compound resistance training 3x/week with 20 minutes of post-workout HIIT or steady-state cardio, staying in a 300-500 calorie deficit."
            "muscle" in lower || "gain" in lower || "hypertrophy" in lower ->
                "Hypertrophy thrives on progressive overload! Focus on 3-4 sets per exercise in the 8-12 rep range with 90 seconds of rest between heavy sets."
            else ->
                "Consistency is the true key to results, ${user.fullName.split(" ").firstOrNull() ?: "athlete"}! Maintain proper form, hit your daily protein goal, and aim for 7-8 hours of quality recovery sleep each night."
        }
    }
}
